package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.CatBearFact;

import greendao.CatBearFactDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig catBearFactDaoConfig;

    private final CatBearFactDao catBearFactDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        catBearFactDaoConfig = daoConfigMap.get(CatBearFactDao.class).clone();
        catBearFactDaoConfig.initIdentityScope(type);

        catBearFactDao = new CatBearFactDao(catBearFactDaoConfig, this);

        registerDao(CatBearFact.class, catBearFactDao);
    }
    
    public void clear() {
        catBearFactDaoConfig.getIdentityScope().clear();
    }

    public CatBearFactDao getCatBearFactDao() {
        return catBearFactDao;
    }

}
